language: scala

scala:
 - 2.11.6

jdk:
  - openjdk7

script:
  # Your normal script
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test

after_success: "sbt coveralls"